version: '3'

services:
  app:
    build: .
    command: yarn start:dev
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: nest-mysql
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=nest
      - MYSQL_DATABASE=nest
      - TZ=America/Belem
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nest-phpmyadmin
    links:
      - db
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - TZ=America/Belem
    depends_on:
      - db